Models/EtkenMaddeViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using ilac_etkilesimleri.Data;
using ilac_etkilesimleri.Plugin.CustomAttributes;
using ilac_etkilesimleri.Plugin.Localization.LanguageResource;

namespace ilac_etkilesimleri.Models
{
    public class EtkenMaddeViewModel
    {
        public EtkenMaddeViewModel()
        {
            EtkilesenEtkenMaddelerId = new List<int>();
            EtkilesenEtkenMaddeler = new List<EtkenMadde>();
        }
        public int Id { get; set; }
        [Display(ResourceType = typeof(Lang), Name = "LabelEtkenMadde"), CustomRequired]
        public string Ad { get; set; }

        [Display(ResourceType = typeof(Lang), Name = "LabelDetail")]
        [AllowHtml]
        public string Aciklama { get; set; }
        public ICollection<int> EtkilesenEtkenMaddelerId { get; set; }
        public ICollection<EtkenMadde> EtkilesenEtkenMaddeler { get; set; }
    }
}

Controllers/EtkenMaddeController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Threading.Tasks;
using System.Net;
using System.Web;
using System.Web.Mvc;
using ilac_etkilesimleri;
using ilac_etkilesimleri.Data;
using ilac_etkilesimleri.Models;

namespace ilac_etkilesimleri.Controllers
{
    [Authorize]
    public class EtkenMaddeController : Controller
    {
        private TingoonDbContext db = new TingoonDbContext();

        // GET: EtkenMadde
        public async Task<ActionResult> Index()
        {
            return View(await db.EtkenMadde.Select(x => new EtkenMaddeListViewModel { Id = x.Id, Ad = x.Ad }).ToListAsync());
        }

        // GET: EtkenMadde/Details/5
        public async Task<ActionResult> Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            EtkenMadde m = await db.EtkenMadde.FindAsync(id);
            if (m == null)
            {
                return HttpNotFound();
            }
            var vm = new EtkenMaddeViewModel
            {
                Id = m.Id,
                Ad = m.Ad,
                Aciklama = m.Aciklama
            };
            var temp = await db.EtkenMaddeEtkilesim.Where(x => x.EtkenMaddeId1 == id || x.EtkenMaddeId2 == id).ToListAsync();
            if (temp != null)
            {
                foreach (var item in temp)
                {
                    if (item.EtkenMaddeId1 == id)
                        vm.EtkilesenEtkenMaddeler.Add(item.EtkenMadde2);
                    else if (item.EtkenMaddeId2 == id)
                        vm.EtkilesenEtkenMaddeler.Add(item.EtkenMadde1);
                }
            }
            return View(vm);
        }

        // GET: EtkenMadde/Create
        public async Task<ActionResult> Create(int? id)
        {
            ViewBag.EtkenMaddeListe = await db.EtkenMadde.Select(x => new SelectListItem { Text = x.Ad, Value = x.Id.ToString() }).ToListAsync();
            return View();
        }

        // POST: EtkenMadde/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create([Bind(Include = "Id,Ad,Aciklama,EtkilesenEtkenMaddelerId")] EtkenMaddeViewModel vm)
        {
            if (!ModelState.IsValid)
            {
                ViewBag.EtkenMaddeListe = await db.EtkenMadde.Select(x => new SelectListItem { Text = x.Ad, Value = x.Id.ToString() }).ToListAsync();
                return View(vm);
            }
            if (db.EtkenMadde.Where(x => x.Ad == vm.Ad.ToLower()).Count() > 0)
            {
                ModelState.AddModelError("Ad", "Bu isimde bir etken madde zaten var.");
                ViewBag.EtkenMaddeListe = await db.EtkenMadde.Select(x => new SelectListItem { Text = x.Ad, Value = x.Id.ToString() }).ToListAsync();
                return View(vm);
            }
            var m = new EtkenMadde
            {
                Ad = vm.Ad.ToLower(),
                Aciklama = vm.Aciklama,
            };
            db.EtkenMadde.Add(m);
            await db.SaveChangesAsync();
            if (vm.EtkilesenEtkenMaddelerId != null && vm.EtkilesenEtkenMaddelerId.Count() > 0)
            {
                foreach (var item in vm.EtkilesenEtkenMaddelerId)
                    db.EtkenMaddeEtkilesim.Add(new EtkenMaddeEtkilesim { EtkenMaddeId1 = m.Id, EtkenMaddeId2 = item });
                await db.SaveChangesAsync();
            }
            return RedirectToAction("Index");
        }

        // GET: EtkenMadde/Edit/5
        public async Task<ActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            EtkenMadde m = await db.EtkenMadde.FindAsync(id);
            if (m == null)
            {
                return HttpNotFound();
            }
            var vm = new EtkenMaddeViewModel
            {
                Id = m.Id,
                Ad = m.Ad,
                Aciklama = m.Aciklama
            };
            var temp = await db.EtkenMaddeEtkilesim.Where(x => x.EtkenMaddeId1 == id || x.EtkenMaddeId2 == id).ToListAsync();
            if (temp != null)
            {
                foreach (var item in temp)
                {
                    if (item.EtkenMaddeId1 == id)
                        vm.EtkilesenEtkenMaddeler.Add(item.EtkenMadde2);
                    else if (item.EtkenMaddeId2 == id)
                        vm.EtkilesenEtkenMaddeler.Add(item.EtkenMadde1);
                }
            }
            foreach (var item in temp)
            {
                if (item.EtkenMaddeId1 == vm.Id)
                    vm.EtkilesenEtkenMaddelerId.Add(item.EtkenMaddeId2);
                else if (item.EtkenMaddeId2 == vm.Id)
                    vm.EtkilesenEtkenMaddelerId.Add(item.EtkenMaddeId1);
            }
            IEnumerable<SelectListItem> items = new MultiSelectList(db.EtkenMadde.Select(x => new SelectListItem { Text = x.Ad, Value = x.Id.ToString() }), "Value", "Text", vm.EtkilesenEtkenMaddelerId);
            ViewBag.EtkenMaddeListe = items;
            //ViewBag.EtkenMaddeListe = new MultiSelectList(db.EtkenMadde.Select(x => new SelectListItem { Text = x.Ad, Value = x.Id.ToString() }), "Value", "Text", vm.EtkilesenEtkenMaddelerId);


            return View(vm);
        }

        // POST: EtkenMadde/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Edit([Bind(Include = "Id,Ad,Aciklama,EtkilesenEtkenMaddelerId")] EtkenMaddeViewModel vm)
        {
            if (!ModelState.IsValid)
            {
                ViewBag.EtkenMaddeListe = new MultiSelectList(db.EtkenMadde.Select(x => new SelectListItem { Text = x.Ad, Value = x.Id.ToString() }), "Value", "Text", vm.EtkilesenEtkenMaddelerId);
                return View(vm);
            }
            EtkenMadde m = await db.EtkenMadde.FindAsync(vm.Id);
            if (m == null)
            {
                return HttpNotFound();
            }
            if (db.EtkenMadde.Where(x => x.Ad == vm.Ad.ToLower() && x.Id != vm.Id).Count() > 0)
            {
                ModelState.AddModelError("Ad", "Bu isimde bir etken madde zaten var.");
                ViewBag.EtkenMaddeListe = new MultiSelectList(db.EtkenMadde.Select(x => new SelectListItem { Text = x.Ad, Value = x.Id.ToString() }), "Value", "Text", vm.EtkilesenEtkenMaddelerId);
                return View(vm);
            }
            m.Ad = vm.Ad;
            m.Aciklama = vm.Aciklama;
            var eskiEtkilesenEtkenMaddeler = await db.EtkenMaddeEtkilesim.Where(x => x.EtkenMaddeId1 == m.Id || x.EtkenMaddeId2 == m.Id).ToListAsync();

            if (eskiEtkilesenEtkenMaddeler == null || eskiEtkilesenEtkenMaddeler.Count == 0)
            {
                foreach (var item in vm.EtkilesenEtkenMaddelerId)
                    db.EtkenMaddeEtkilesim.Add(new EtkenMaddeEtkilesim { EtkenMaddeId1 = m.Id, EtkenMaddeId2 = item });
            }
            else
            {
                if (vm.EtkilesenEtkenMaddelerId == null || vm.EtkilesenEtkenMaddelerId.Count() == 0)
                {
                    db.EtkenMaddeEtkilesim.RemoveRange(eskiEtkilesenEtkenMaddeler);
                }
                else
                {
                    List<int> eskiEtkilesenEtkenMaddelerId = new List<int>();
                    foreach (var item in eskiEtkilesenEtkenMaddeler)
                    {
                        if (item.EtkenMaddeId1 == vm.Id)
                            eskiEtkilesenEtkenMaddelerId.Add(item.EtkenMaddeId2);
                        else if (item.EtkenMaddeId2 == vm.Id)
                            eskiEtkilesenEtkenMaddelerId.Add(item.EtkenMaddeId1);
                    }

                    var yeniEtkilesenEtkenMaddeFark = vm.EtkilesenEtkenMaddelerId.Except(eskiEtkilesenEtkenMaddelerId);
                    if (yeniEtkilesenEtkenMaddeFark != null && yeniEtkilesenEtkenMaddeFark.Count()>0)
                    {
                        foreach (var item in yeniEtkilesenEtkenMaddeFark)
                            db.EtkenMaddeEtkilesim.Add(new EtkenMaddeEtkilesim { EtkenMaddeId1 = m.Id, EtkenMaddeId2 = item });
                    }
                    var eskiEtkilesenEtkenMaddeFark = eskiEtkilesenEtkenMaddelerId.Except(vm.EtkilesenEtkenMaddelerId);
                    if (eskiEtkilesenEtkenMaddeFark != null && eskiEtkilesenEtkenMaddeFark.Count() > 0)
                    {
                        db.EtkenMaddeEtkilesim.RemoveRange(eskiEtkilesenEtkenMaddeler.Where(x => eskiEtkilesenEtkenMaddeFark.Contains(x.EtkenMaddeId1) || eskiEtkilesenEtkenMaddeFark.Contains(x.EtkenMaddeId2)));
                    }

                }

            }
            db.Entry(m).State = EntityState.Modified;

            await db.SaveChangesAsync();
            return RedirectToAction("Index");
        }

        // GET: EtkenMadde/Delete/5
        public async Task<ActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            EtkenMadde m = await db.EtkenMadde.FindAsync(id);
            if (m == null)
            {
                return HttpNotFound();
            }
            var vm = new EtkenMaddeViewModel
            {
                Id = m.Id,
                Ad = m.Ad,
                Aciklama = m.Aciklama
            };

Views/EtkenMadde/Create.cshtml
@model ilac_etkilesimleri.Models.EtkenMaddeViewModel

@{
    /**/

    ViewBag.process = "Oluştur";
    ViewBag.Title = "Etken Madde";
}

@section head{
    <!-- Select2 -->
    <link rel="stylesheet" href="~/Assets/bower_components/select2/dist/css/select2.min.css">
}
@section scripts{
    <!-- Select2 -->
    <script src="~/Assets/bower_components/select2/dist/js/select2.full.min.js"></script>
    <script>
        $(function () {
            //Initialize Select2 Elements
            $('.select2').select2()
        })
    </script>
    <!-- CK Editor -->
    <script src="~/Assets/bower_components/ckeditor/ckeditor.js"></script>
    <script>
        $(function () {
            // Replace the <textarea id="editor1"> with a CKEditor
            // instance, using default configuration.
            CKEDITOR.replace('Aciklama')
        })
    </script>

}
<div class="box">
    <div class="box-header">
        <h3 class="box-title"><b>@ViewBag.Title Oluştur</b> </h3>
    </div>
</div>
@using (Html.BeginForm())
{<div class="box">
        @Html.AntiForgeryToken()
        <div class="form-horizontal">
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            <div class="form-group">
                @Html.LabelFor(model => model.Ad, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Ad, new { htmlAttributes = new { @class = "form-control", @required = "required" } })
                    @Html.ValidationMessageFor(model => model.Ad, "", new { @class = "text-danger" })
                </div>
            </div>
            <div class="form-group">
                @Html.LabelFor(model => model.Aciklama, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.TextAreaFor(model => model.Aciklama, new { htmlAttributes = new { @class = "form-control", @required = "required", @rows = "10", @cols = "80" } })
                    @Html.ValidationMessageFor(model => model.Aciklama, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>
    </div>
    <div class="box">
        <div class="form-horizontal">
            @if (ViewBag.EtkenMaddeListe != null)
            {
                <div class="form-group">
                    @Html.LabelFor(model => model.EtkilesenEtkenMaddeler, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.DropDownListFor(model => model.EtkilesenEtkenMaddelerId, ViewBag.EtkenMaddeListe as IEnumerable<SelectListItem>, htmlAttributes: new { @class = "form-control select2", @multiple = "multiple", @data_placeholder = "Seçiniz", @style = "width: 100%;" })                        @Html.ValidationMessageFor(model => model.EtkilesenEtkenMaddelerId, "", new { @class = "text-danger" })
                    </div>
                </div>
            }
        </div>
    </div>
    <div class="box">
        <div class="form-group">
            <div class=" col-md-6">

                <input type="submit" value="Kaydet" class="btn btn-block btn-primary btn-lg" />
            </div>
            <div class=" col-md-6">
                @Html.ActionLink("Listeye Geri Dön", "Index", null, htmlAttributes: new { @class = "btn btn-block btn-warning btn-lg" })
            </div>
        </div>
    </div>
}

Views/EtkenMadde/Delete.cshtml
@model ilac_etkilesimleri.Models.EtkenMaddeViewModel

@{
    ViewBag.process = Model.Ad;
    ViewBag.Title = "Etken Madde";
}
<div class="box">
    <div class="box-header">
        <h3 class="box-title"><b>@ViewBag.Title 'yi GErçekten Silmek İstiyor Musunuz?</b> </h3>
    </div>
</div>
<div class="box">
    <div class="box-header">
        <h3 class="box-title"> <b>@Html.DisplayNameFor(model => model.Id)</b></h3>
        <p>
            @Model.Id
        </p>
    </div>
    <div class="box-header">
        <h3 class="box-title"> <b>@Html.DisplayNameFor(model => model.Ad)</b></h3>
        <p>
            @Model.Ad
        </p>
    </div>
    <div class="box-header">
        <h3 class="box-title"> <b>@Html.DisplayNameFor(model => model.Aciklama)</b></h3>
        <p>
            @Html.Raw(Model.Aciklama)
        </p>
    </div>
</div>
<div class="box">
    <div class="box-header">
        <h4 class="box-title Bold"><b>Etkileşimde Bulunduğu Etken Maddeler</b></h4>
    </div>
    @if (Model.EtkilesenEtkenMaddeler != null && Model.EtkilesenEtkenMaddeler.Count > 0)
    {

        foreach (var item in Model.EtkilesenEtkenMaddeler)
        {
            <div class="box box-default collapsed-box">
                <div class="box-header with-border">
                    <h3 class="box-title">@item.Ad</h3>

                    <div class="box-tools pull-right">
                        <a class="btn btn-box-tool" href="@Url.Action("Details","EtkenMadde", new { id = item.Id })">
                            <i class="fa fa-external-link-square"></i>
                        </a>
                        <button type="button" class="btn btn-box-tool" data-widget="collapse">
                            <i class="fa fa-plus"></i>
                        </button>

                    </div>
                    <!-- /.box-tools -->
                </div>
                <!-- /.box-header -->
                <div class="box-body">
                    @Html.Raw(item.Aciklama)
                </div>
                <!-- /.box-body -->
            </div>
        }

    }
    else
    {
        <span>Etkilesen madde eklenmemiştir.</span>
    }
</div>
<div class="box">
    <div class="form-horizontal">
        @using (Html.BeginForm())
        {
            @Html.AntiForgeryToken()

            <div class="form-group">
                <div class="col-md-6">
                    <input type="submit" value="Delete" class="btn btn-block btn-danger btn-lg" />
                </div>
                <div class="col-md-6">
                    @Html.ActionLink("Listeye Geri Dön", "Index", null, htmlAttributes: new { @class = "btn btn-block btn-warning btn-lg" })
                </div>
            </div>
        }
    </div>
</div>

Views/EtkenMadde/Details.cshtml
@model ilac_etkilesimleri.Models.EtkenMaddeViewModel

@{
    ViewBag.process = Model.Ad;
    ViewBag.Title = "Etken Madde";
}
<div class="box">
    <div class="box-header">
        <h3 class="box-title"><b>@ViewBag.Title Detayları</b> </h3>
    </div>
</div>
<div class="box">
    <div class="box-header">
        <h3 class="box-title"> <b>@Html.DisplayNameFor(model => model.Id)</b></h3>
        <p>
            @Model.Id
        </p>
    </div>
    <div class="box-header">
        <h3 class="box-title"> <b>@Html.DisplayNameFor(model => model.Ad)</b></h3>
        <p>
            @Model.Ad
        </p>
    </div>
    <div class="box-header">
        <h3 class="box-title"> <b>@Html.DisplayNameFor(model => model.Aciklama)</b></h3>
        <p>
            @Html.Raw(Model.Aciklama)
        </p>
    </div>
</div>
<div class="box">
    <div class="box-header">
        <h4 class="box-title Bold"><b>Etkileşimde Bulunduğu Etken Maddeler</b></h4>
    </div>
    @if (Model.EtkilesenEtkenMaddeler != null && Model.EtkilesenEtkenMaddeler.Count > 0)
    {

        foreach (var item in Model.EtkilesenEtkenMaddeler)
        {
            <div class="box box-default collapsed-box">
                <div class="box-header with-border">
                    <h3 class="box-title">@item.Ad</h3>

                    <div class="box-tools pull-right">
                        <a class="btn btn-box-tool" href="@Url.Action("Details","EtkenMadde", new { id = item.Id })">
                            <i class="fa fa-external-link-square"></i>
                        </a>
                        <button type="button" class="btn btn-box-tool" data-widget="collapse">
                            <i class="fa fa-plus"></i>
                        </button>

                    </div>
                    <!-- /.box-tools -->
                </div>
                <!-- /.box-header -->
                <div class="box-body">
                    @Html.Raw(item.Aciklama)
                </div>
                <!-- /.box-body -->
            </div>
        }

    }
    else
    {
        <span>Etkilesen madde eklenmemiştir.</span>
    }

</div>
<div class="box">
    <div class="form-horizontal">
        <div class="form-group">
            <div class="col-md-6">
                @Html.ActionLink("Düzenle", "Edit", new { id = Model.Id }, htmlAttributes: new { @class = "btn btn-block btn-primary btn-lg" })
            </div>
            <div class="col-md-6">
                @Html.ActionLink("Listeye Geri Dön", "Index", null, htmlAttributes: new { @class = "btn btn-block btn-warning btn-lg" })
            </div>
        </div>
    </div>
</div>

Views/EtkenMadde/Edit.cshtml
@model ilac_etkilesimleri.Models.EtkenMaddeViewModel

@{
    ViewBag.process = "Güncelle";
    ViewBag.Title = "Etken Madde";
}
@section head{
    <!-- Select2 -->
    <link rel="stylesheet" href="~/Assets/bower_components/select2/dist/css/select2.min.css">
}
@section scripts{
    <!-- Select2 -->
    <script src="~/Assets/bower_components/select2/dist/js/select2.full.min.js"></script>
    <script>
        $(function () {
            //Initialize Select2 Elements
            $('.select2').select2()
        })
    </script>
    <!-- CK Editor -->
    <script src="~/Assets/bower_components/ckeditor/ckeditor.js"></script>
    <script>
        $(function () {
            // Replace the <textarea id="editor1"> with a CKEditor
            // instance, using default configuration.
            CKEDITOR.replace('Aciklama')
        })
    </script>
}

    <div class="box">
        <div class="box-header">
            <h3 class="box-title"><b>@ViewBag.Title Güncelle</b> </h3>
        </div>
    </div>
@using (Html.BeginForm())
{
    <div class="box">
        @Html.AntiForgeryToken()

        <div class="form-horizontal">

            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            <div class="form-group">
                @Html.LabelFor(model => model.Id, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Model.Id
                </div>
            </div>
            <div class="form-group">
                @Html.LabelFor(model => model.Ad, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Ad, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Ad, "", new { @class = "text-danger" })
                </div>
            </div>
            <div class="form-group">
                @Html.LabelFor(model => model.Aciklama, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.TextAreaFor(model => model.Aciklama, new { htmlAttributes = new { @class = "form-control", @rows = "10", @cols = "80" } })
                    @Html.ValidationMessageFor(model => model.Aciklama, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>
    </div>
    <div class="box">
        <div class="form-horizontal">
            @if (ViewBag.EtkenMaddeListe != null)
            {
                <div class="form-group">
                    @Html.LabelFor(model => model.EtkilesenEtkenMaddeler, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.DropDownListFor(model => model.EtkilesenEtkenMaddelerId, ViewBag.EtkenMaddeListe as MultiSelectList, htmlAttributes: new { @class = "form-control select2", @multiple = "multiple", @data_placeholder = "Seçiniz", @style = "width: 100%;" })
                        @Html.ValidationMessageFor(model => model.EtkilesenEtkenMaddelerId, "", new { @class = "text-danger" })
                    </div>
                </div>
            }
        </div>
    </div>
    <div class="box">
        <div class="form-horizontal">
            <div class="form-group">
                <div class="col-md-6">
                    <input type="submit" value="Güncelle" class="btn btn-block btn-primary btn-lg" />
                </div>
                <div class="col-md-6">
                    @Html.ActionLink("Listeye Geri Dön", "Index", null, htmlAttributes: new { @class = "btn btn-block btn-warning btn-lg" })
                </div>
            </div>
        </div>
    </div>
}

Views/EtkenMadde/Index.cshtml
@model IEnumerable<ilac_etkilesimleri.Models.EtkenMaddeListViewModel>

@{
    ViewBag.process = "Liste";
    ViewBag.Title = "Etken Madde";
}

@section head{
    <!-- Select2 -->
    <link rel="stylesheet" href="~/Assets/bower_components/select2/dist/css/select2.min.css">
    <!-- DataTables -->
    <link rel="stylesheet" href="~/Assets/bower_components/datatables.net-bs/css/dataTables.bootstrap.min.css">

}
@section scripts{
    <!-- DataTables -->
    <script src="~/Assets/bower_components/datatables.net/js/jquery.dataTables.min.js"></script>
    <script src="~/Assets/bower_components/datatables.net-bs/js/dataTables.bootstrap.min.js"></script>
    <script type="text/javascript">
        $(function () {
            $('#example1').DataTable()
            $('#example2').DataTable({
                'paging': true,
                'lengthChange': false,
                'searching': false,
                'ordering': true,
                'info': true,
                'autoWidth': false
            })
        })
    </script>
}
<div class="box">
    <div class="box-header">
        <h3 class="box-title"><b>@ViewBag.Title Liste</b> </h3>
    </div>
</div>
<div class="box">
    <div class="box-header">
        <a href='@Url.Action("Create")' class='btn btn-primary'>Etken Madde Oluştur</a>
    </div>
    <!-- /.box-header -->
    <div class="box-body">
        <table id="example1" class="table table-bordered table-striped">
            <thead>
                <tr>
                    @*Değiştirlecek*@
                    <th>
                        @Html.DisplayNameFor(model => model.Id)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.Ad)
                    </th>
                    <th>İşlemler</th>
                </tr>
            </thead>
            <tbody>
                @foreach (var item in Model)
                {
                    <tr>
                        <td>
                            @item.Id
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.Ad)
                        </td>
                        <td>
                            <a href='@Url.Action("Details",new { id= item.Id })' class='btn btn-primary'><div class="col-md-3 col-sm-4"><i class="fa fa-fw fa-building-o"></i></div></a>
                            <a href='@Url.Action("Edit",new { id= item.Id })' class='btn btn-warning'><span class="glyphicon glyphicon-edit"></span></a>
                            <a href='@Url.Action("Delete",new { id= item.Id })' class='btn btn-danger'><span class="glyphicon glyphicon-trash"></span></a>
                        </td>
                    </tr>
                }
            </tbody>
            <tfoot>
                <tr>
                    <th>
                        @Html.DisplayNameFor(model => model.Ad)
                    </th>
                    <th>İşlemler</th>
                </tr>
            </tfoot>
        </table>
    </div>
    <!-- /.box-body -->
</div>